feat: Added option to set guaranteed resource on waggledance pod
ExpediaGroup/apiary-federation pull request #143
Opened 2024-04-17 17:56 UTC by githubjianli

### :pencil: Description
- 
Pod evicted due to `OOMKilled`.

### :link: Related Issues
-

2024-04-17 20:09 UTC, mroark1m approved these changes
LGTM!

2024-04-18 07:26 UTC, patduin requested changes
I think we should move away from these derived values and have just explicit variable for the memory/cpu requests and limit and they are used as is without anything else.
Same for heapsize, we can have defaults if needed or a comment saying 85% of request should be for heap but deriving them makes it hard to tinker.

2024-04-18 15:59 UTC, patduin approved these changes

2024-04-18 16:13 UTC, mroark1m approved these changes

2024-04-18 16:57 UTC, merged